document.writeln("<div id=\'offcanvas-nav\' uk-offcanvas=\'overlay: true;\'>");
document.writeln("    <div class=\'uk-offcanvas-bar\'>");
document.writeln("        <ul class=\'uk-nav uk-nav-default uk-container-center\' uk-nav>");
document.writeln("            <li><hr class=\'uk-nav-divider\'></li>");
document.writeln("            <li class=\'uk-parent\'>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <div class=\'uk-inline\'>");
document.writeln("                        <img class=\'bar-img-size\' src=\'../static/img/province/北京市.jpg\' alt=\'北京\'>");
document.writeln("                        <div class=\'uk-overlay uk-position-center\'><h3 class=\'font\'>北京市</h3></div>");
document.writeln("                    </div>");
document.writeln("                </a>");
document.writeln("                <ul class=\'uk-nav-sub\'>");
document.writeln("                    <li class=\'uk-parent\'>");
document.writeln("                        <a href=\'#\'>东城区</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>西城区</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>朝阳区</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("            <li><hr class=\'uk-nav-divider\'></li>");
document.writeln("            <li class=\'uk-parent\'>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <div class=\'uk-inline\'>");
document.writeln("                        <img class=\'bar-img-size\' src=\'../static/img/province/天津.jpg\' alt=\'天津\'>");
document.writeln("                        <div class=\'uk-overlay uk-position-center\'><h3 class=\'font\'>天津市</h3></div>");
document.writeln("                    </div>");
document.writeln("                </a>");
document.writeln("                <ul class=\'uk-nav-sub\' uk-nav>");
document.writeln("                    <li class=\'uk-parent\'>");
document.writeln("                        <a href=\'#\'>河东区</a>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>河西区</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("            <li><hr class=\'uk-nav-divider\'></li>");
document.writeln("            <li class=\'uk-parent\'>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <div class=\'uk-inline\'>");
document.writeln("                        <img class=\'bar-img-size\' src=\'../static/img/province/河北.jpg\' alt=\'河北\'>");
document.writeln("                        <div class=\'uk-overlay uk-position-center\'><h3 class=\'font\'>河北省</h3></div>");
document.writeln("                    </div>");
document.writeln("                </a>");
document.writeln("                <ul class=\'uk-nav-sub\' uk-nav>");
document.writeln("                    <li class=\'uk-parent\'>");
document.writeln("                        <a href=\'#\' uk-icon=\'chevron-down\'>石家庄市</a>");
document.writeln("                        <ul>");
document.writeln("                            <li><a>长安区</a></li>");
document.writeln("                            <li><a>桥西区</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>唐山市</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("            <li><hr class=\'uk-nav-divider\'></li>");
document.writeln("            <li class=\'uk-parent\'>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <div class=\'uk-inline\'>");
document.writeln("                        <img class=\'bar-img-size\' src=\'../static/img/province/山西.jpg\' alt=\'山西\'>");
document.writeln("                        <div class=\'uk-overlay uk-position-center\'><h3 class=\'font\'>山西省</h3></div>");
document.writeln("                    </div>");
document.writeln("                </a>");
document.writeln("                <ul class=\'uk-nav-sub\' uk-nav>");
document.writeln("                    <li class=\'uk-parent\'>");
document.writeln("                        <a href=\'#\' uk-icon=\'chevron-down\'>太原市</a>");
document.writeln("                        <ul>");
document.writeln("                            <li><a>小店区</a></li>");
document.writeln("                            <li><a>迎泽区</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>大同市</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("            <li><hr class=\'uk-nav-divider\'></li>");
document.writeln("            <li class=\'uk-parent\'>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <div class=\'uk-inline\'>");
document.writeln("                        <img class=\'bar-img-size\' src=\'../static/img/province/内蒙古.jpg\' alt=\'内蒙古\'>");
document.writeln("                        <div class=\'uk-overlay uk-position-center\'><h3 class=\'font\'>内蒙古省</h3></div>");
document.writeln("                    </div>");
document.writeln("                </a>");
document.writeln("                <ul class=\'uk-nav-sub\' uk-nav>");
document.writeln("                    <li class=\'uk-parent\'>");
document.writeln("                        <a href=\'#\' uk-icon=\'chevron-down\'>呼和浩特市</a>");
document.writeln("                        <ul>");
document.writeln("                            <li><a>新城区</a></li>");
document.writeln("                            <li><a>回民区</a></li>");
document.writeln("                            <li><a>和林格尔县</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>包头市</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("            <li><hr class=\'uk-nav-divider\'></li>");
document.writeln("            <li class=\'uk-parent\'>");
document.writeln("                <a href=\'#\'>");
document.writeln("                    <div class=\'uk-inline\'>");
document.writeln("                        <img class=\'bar-img-size\' src=\'../static/img/province/辽宁.jpg\' alt=\'辽宁\'>");
document.writeln("                        <div class=\'uk-overlay uk-position-center\'><h3 class=\'font\'>辽宁省</h3></div>");
document.writeln("                    </div>");
document.writeln("                </a>");
document.writeln("                <ul class=\'uk-nav-sub\' uk-nav>");
document.writeln("                    <li class=\'uk-parent\'>");
document.writeln("                        <a href=\'#\' uk-icon=\'chevron-down\'>沈阳市</a>");
document.writeln("                        <ul>");
document.writeln("                            <li><a>和平区</a></li>");
document.writeln("                            <li><a>沈河区</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </li>");
document.writeln("                    <li>");
document.writeln("                        <a href=\'#\'>大连市</a>");
document.writeln("                    </li>");
document.writeln("                </ul>");
document.writeln("            </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");